# Generated by Django 5.0.3 on 2024-04-18 10:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('number_of_beds', models.SmallIntegerField()),
                ('roomType', models.CharField(choices=[('Deluxe', 'Room'), ('Superior', 'Room'), ('Double', 'Room'), ('Junior', 'Suite'), ('Family', 'Room')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=200)),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('date_of_reservation', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.user')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rooms.room')),
            ],
        ),
    ]
