# Generated by Django 5.0 on 2024-04-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='roomType',
            new_name='room_type',
        ),
    ]
