# Generated by Django 5.0 on 2024-05-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image_for_room',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
