# Generated by Django 5.0 on 2024-05-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_room_room_type_images_roomimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
